# Generated by Django 6.0.6 on 2026-07-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(help_text='Нужно для авторизации сотрудников, чтобы отслеживать их премию', verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('role', models.CharField(choices=[('ai_creator', 'Специалист по генерации контента'), ('searchman', 'Специалист по поиску товаров'), ('uploader', 'Заполнитель админ-панели')], max_length=50, verbose_name='Роль')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('zh', '中文')], default='ru', max_length=5, verbose_name='Язык бота')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст (Необязательно)')),
                ('tg_id', models.BigIntegerField(blank=True, help_text='Нужно для авторизации сотрудников, чтобы отслеживать их премию', null=True, verbose_name='Telegram ID')),
                ('registred', models.BooleanField(default=False, verbose_name='Уже вошли в бота?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.CharField(blank=True, default='', max_length=255, verbose_name='Цена')),
                ('size', models.CharField(max_length=100, verbose_name='Размеры')),
                ('color', models.CharField(max_length=100, verbose_name='Цвета')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('characteristics', models.CharField(max_length=100, verbose_name='Характеристики')),
                ('packaging', models.CharField(max_length=100, verbose_name='Комплектация')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Загружено в панель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='staff.image', verbose_name='Фотки товара')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='staff.image', verbose_name='Главная фотка товара')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_products', to='staff.staff', verbose_name='Поисковик')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_products', to='staff.staff', verbose_name='Загрузчик в панель')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар от поисковика',
                'verbose_name_plural': 'Товары от поисковика',
            },
        ),
        migrations.CreateModel(
            name='AiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.product', verbose_name='Продукт ии-изображения')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Создатель ии-изображения')),
            ],
            options={
                'verbose_name': 'ИИ-Изображение',
                'verbose_name_plural': 'ИИ-Изображения',
            },
        ),
    ]
